# Generated by Django 4.2.6 on 2024-01-05 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_cash_currency_cash_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('place', models.CharField(max_length=128)),
                ('purchase_type', models.CharField(max_length=128)),
                ('amount', models.FloatField()),
                ('note', models.CharField(max_length=512)),
                ('cash', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_items', to='expenses.cash')),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_cards', to='expenses.creditcard')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
