# Generated by Django 4.2.6 on 2024-01-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='cash_amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='credit_card_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
