# Generated by Django 4.2.6 on 2024-01-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_payment_cash_alter_payment_cash_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cash_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='credit_card_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
