# Generated by Django 4.2.6 on 2024-01-09 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_payment_cash_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=48)),
                ('currency', models.CharField(max_length=16)),
                ('reminder', models.FloatField()),
                ('expiried_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=512)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
