# Generated by Django 4.2.6 on 2024-01-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_debitcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitcard',
            name='expiried_date',
        ),
    ]
