# Generated by Django 4.2.6 on 2024-01-14 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_payment_debit_card_payment_debit_card_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='creditcard',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='credit_card_currencies', to='expenses.currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cash',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_currencies', to='expenses.currency'),
        ),
        migrations.AlterField(
            model_name='debitcard',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_card_currencies', to='expenses.currency'),
        ),
    ]
