# Generated by Django 4.2.6 on 2024-01-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_alter_cash_owner_currency_creditcard_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='debitcard',
            name='currency',
        ),
    ]
