# Generated by Django 4.2.6 on 2024-01-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_remove_cash_currency_remove_creditcard_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cash_currencies', to='expenses.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debitcard',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='debit_card_currencies', to='expenses.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payment_currencies', to='expenses.currency'),
            preserve_default=False,
        ),
    ]
