# Generated by Django 4.2.6 on 2024-01-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_cash_currency_debitcard_currency_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='currency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_currencies', to='expenses.currency'),
        ),
        migrations.AlterField(
            model_name='debitcard',
            name='currency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_card_currencies', to='expenses.currency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_currencies', to='expenses.currency'),
        ),
    ]
