# Generated by Django 4.2.6 on 2024-01-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_creditcard_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='debitcard',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
    ]
